runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/site/layouts/index.html
  upload: www/site/layouts/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
